/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_jsiwng_primitiva;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class LogIn extends javax.swing.JFrame {

    private String sEmail;
    private String sContra;
    private String sDNI;
    private boolean bUser = true;
    private String cliente = null;
    public static String[] usuario;
    public static String[] login_usuario;
    public static String[] wins_usuario;

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    public String buscarEmail(String email, String passw) {
        String sDNI = "error";  // Valor por defecto si no se encuentra
        String parametros = email + " " + passw;
        login_usuario = parametros.split("\\s+");
        String consulta = "SELECT NIF FROM tb_usuarios WHERE Correo_electronico = ? AND password = ?";

        try {
            var conn = ConexionBaseDatos.getConnection();
            PreparedStatement ps = conn.prepareStatement(consulta);
            ps.setString(1, email);
            ps.setString(2, passw);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    sDNI = rs.getString("NIF");  // Se asigna el NIF real
                }
            }

        } catch (SQLException e) {
            System.err.println("Error al buscar el email en la base de datos: " + e.getMessage());
        }

        return sDNI;
    }

    public String verVictorias(String dni) {
        String parametros="";
        try {
            var conn = ConexionBaseDatos.getConnection();
            if (conn != null) {
                var stmt = conn.prepareStatement("SELECT * FROM tb_victorias_usuarios WHERE NIF=?");
                stmt.setString(1, sDNI);
                var resultado = stmt.executeQuery();
                if (resultado.next()) {
                    String bingo = resultado.getString(2);
                    String primitiva = resultado.getString(3);
                    parametros = bingo + " " + primitiva;
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al buscar el email en la base de datos: " + e.getMessage());
        }
        return parametros;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombreLoteria = new javax.swing.JLabel();
        labelRegistrarLoteria = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        TextoPassw = new javax.swing.JPasswordField();
        labelEmail = new javax.swing.JLabel();
        TextoEmail = new javax.swing.JTextField();
        labelPassw = new javax.swing.JLabel();
        btnIrRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        labelNombreLoteria.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria.setText("Loterias Timo-Theo");
        labelNombreLoteria.setOpaque(true);

        labelRegistrarLoteria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelRegistrarLoteria.setForeground(new java.awt.Color(255, 255, 255));
        labelRegistrarLoteria.setText("Recuerdame quien eres:");

        btnAtras.setBackground(new java.awt.Color(0, 153, 0));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setBackground(new java.awt.Color(0, 153, 0));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        TextoPassw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoPassw.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoPasswCaretUpdate(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmail.setText("Correo electronico");

        TextoEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoEmail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoEmailCaretUpdate(evt);
            }
        });

        labelPassw.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPassw.setForeground(new java.awt.Color(255, 255, 255));
        labelPassw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPassw.setText("Contraseña");

        btnIrRegistrar.setBackground(new java.awt.Color(0, 102, 0));
        btnIrRegistrar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnIrRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnIrRegistrar.setText("No tienes cuenta: Registrate");
        btnIrRegistrar.setBorderPainted(false);
        btnIrRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 103, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TextoPassw, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextoEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnIrRegistrar))
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelRegistrarLoteria, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPassw, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRegistrarLoteria)
                .addGap(24, 24, 24)
                .addComponent(labelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPassw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoPassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIrRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        Panel_inicial.startPanel();
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        this.sDNI = buscarEmail(sEmail, sContra);
        wins_usuario = verVictorias(sDNI).split("\\s+");
        if (!this.sDNI.equals("error")) {
            try {
                var conn = ConexionBaseDatos.getConnection();
                if (conn != null) {
                    var stmt = conn.prepareStatement("SELECT * FROM tb_datos_usuarios WHERE NIF=?");
                    stmt.setString(1, sDNI);
                    var resultado = stmt.executeQuery();
                    if (resultado.next()) {
                        String nombre = resultado.getString(2);
                        String apellido1 = resultado.getString(3);
                        String apellido2 = resultado.getString(4);
                        String fechaNaci = resultado.getString(5);
                        cliente = sDNI + " " + nombre + " " + apellido1 + " " + apellido2 + " " + fechaNaci;
                        usuario = cliente.split("\\s+");
                        JOptionPane.showMessageDialog(jPanel1, "Bienvenido: " + usuario[1] + " " + usuario[2] + " " + usuario[3]);
                    } else {
                        JOptionPane.showMessageDialog(null, "Cliente no encontrado.");
                    }
                    stmt.close();
                    conn.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(jPanel1, "Error al buscar al cliente: " + e.getMessage());
                bUser = false;
            }
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Email o contraseña incorrectos.");
            bUser = false;
        }

        if (!sDNI.equals("77964837N") && bUser == true) {
            new Menu_principal().setVisible(true);
            dispose();
        } else if (sDNI.equals("77964837N")) {
            new Menu_principal_admin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnIrRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrRegistrarActionPerformed
        // TODO add your handling code here:
        new Registrar().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIrRegistrarActionPerformed

    private void TextoEmailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoEmailCaretUpdate
        // TODO add your handling code here:
        this.sEmail = TextoEmail.getText();
    }//GEN-LAST:event_TextoEmailCaretUpdate

    private void TextoPasswCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoPasswCaretUpdate
        // TODO add your handling code here:
        this.sContra = new String(TextoPassw.getPassword());;

    }//GEN-LAST:event_TextoPasswCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextoEmail;
    private javax.swing.JPasswordField TextoPassw;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnIrRegistrar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNombreLoteria;
    private javax.swing.JLabel labelPassw;
    private javax.swing.JLabel labelRegistrarLoteria;
    // End of variables declaration//GEN-END:variables
}
