/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_jsiwng_primitiva;

import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class MenuDatosUsuario extends javax.swing.JFrame {

    private String sDNI;
    private String sNombre;
    private String sApellido1;
    private String sApellido2;
    private String sFechaNaci;
    private String sCorreo;
    private String sContra;
    private boolean bErrorDNI = true;
    private boolean bErrorContra = true;
    private boolean bErrorEmail = true;
    private boolean bErrorFecha = true;
    private boolean bErrorNull = true;
    private boolean bDNIcambiado = false;

    /**
     * Creates new form MenuDatosUsuario
     */
    
    public boolean validar() {
        if (bErrorDNI == true) {
            JOptionPane.showMessageDialog(jPanel1, "DNI inválido. Debe tener 8 números y una letra mayúscula.");
        } else if (bErrorEmail == true) {
            JOptionPane.showMessageDialog(jPanel1, "Correo electronico inválido.");
        } else if (bErrorContra == true) {
            JOptionPane.showMessageDialog(jPanel1, "Contraseña inválida. Debe tener 1 caracter minimo.");
        } else if (bErrorFecha == true) {
            JOptionPane.showMessageDialog(jPanel1, "Fecha nacimiento inválida. Debe tener un formato de fecha (dd/mm/yyyy).");
        } else if (bErrorNull == true) {
            JOptionPane.showMessageDialog(jPanel1, "No puede haber campos vacios.");
        } else {
            return true;
        }
        return false;
    }
    
    public MenuDatosUsuario() {
        initComponents();
        TextoDNI.setText(LogIn.usuario[0]);
        TextoNombre.setText(LogIn.usuario[1]);
        TextoApellido1.setText(LogIn.usuario[2]);
        TextoApellido2.setText(LogIn.usuario[3]);
        TextoFechaNaci.setText(LogIn.usuario[4]);
        TextoCorreo.setText(LogIn.login_usuario[0]);
        TextoContra.setText(LogIn.login_usuario[1]);
        TextoWInBingo.setText(LogIn.wins_usuario[0]);
        TextoWinPrimitiva.setText(LogIn.wins_usuario[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombreLoteria1 = new javax.swing.JLabel();
        labelDNI = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelFechaNaci = new javax.swing.JLabel();
        labelApellido1 = new javax.swing.JLabel();
        labelApellido2 = new javax.swing.JLabel();
        labelbingoWin = new javax.swing.JLabel();
        labelbingoWin1 = new javax.swing.JLabel();
        TextoApellido1 = new javax.swing.JTextField();
        TextoDNI = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoApellido2 = new javax.swing.JTextField();
        TextoFechaNaci = new javax.swing.JTextField();
        TextoWInBingo = new javax.swing.JTextField();
        TextoWinPrimitiva = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        labelFechaNaci1 = new javax.swing.JLabel();
        labelApellido3 = new javax.swing.JLabel();
        TextoCorreo = new javax.swing.JTextField();
        TextoContra = new javax.swing.JPasswordField();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        labelNombreLoteria1.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria1.setText("Loterias Timo-Theo");
        labelNombreLoteria1.setOpaque(true);

        labelDNI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI.setText("DNI:");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre:");

        labelFechaNaci.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFechaNaci.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNaci.setText("Fecha nacimiento(dd/mm/aaaa):");

        labelApellido1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido1.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido1.setText("Primer apellido:");

        labelApellido2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido2.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido2.setText("Segundo apellido:");

        labelbingoWin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin.setText("Victorias en el bingo:");

        labelbingoWin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin1.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin1.setText("Victorias en la primitiva:");

        TextoApellido1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoApellido1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoApellido1CaretUpdate(evt);
            }
        });

        TextoDNI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoDNICaretUpdate(evt);
            }
        });

        TextoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoNombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoNombreCaretUpdate(evt);
            }
        });

        TextoApellido2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoApellido2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoApellido2CaretUpdate(evt);
            }
        });

        TextoFechaNaci.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoFechaNaci.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoFechaNaciCaretUpdate(evt);
            }
        });

        TextoWInBingo.setEditable(false);
        TextoWInBingo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        TextoWinPrimitiva.setEditable(false);
        TextoWinPrimitiva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnModificar.setBackground(new java.awt.Color(0, 153, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Guardar cambios");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        labelFechaNaci1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFechaNaci1.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNaci1.setText("Contraseña:");

        labelApellido3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido3.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido3.setText("Correo electronico:");

        TextoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoCorreo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoCorreoCaretUpdate(evt);
            }
        });

        TextoContra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoContra.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoContraCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelbingoWin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelbingoWin1))
                                .addGap(209, 218, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextoWinPrimitiva)
                                    .addComponent(TextoWInBingo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelFechaNaci1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoContra, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDNI)
                    .addComponent(TextoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido1)
                    .addComponent(TextoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaNaci)
                    .addComponent(TextoFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaNaci1)
                    .addComponent(TextoContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelbingoWin)
                    .addComponent(TextoWInBingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelbingoWin1)
                    .addComponent(TextoWinPrimitiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (validar()){
            try {
                if (bDNIcambiado) {
                    if (Registrar.SQLComprobarCliente(sDNI)) {
                        throw new Exception();
                    }
                }

                var conn = ConexionBaseDatos.getConnection();
                if (conn != null) {
                    
                    var stmt = conn.prepareStatement("UPDATE tb_victorias_usuarios SET NIF = ?, victorias_bingo = ?, victorias_primitiva = ? WHERE tb_victorias_usuarios.NIF = ?;");
                    stmt.setString(1, sDNI);
                    stmt.setInt(2, Integer.parseInt(LogIn.wins_usuario[0]));
                    stmt.setInt(3, Integer.parseInt(LogIn.wins_usuario[1]));
                    stmt.setString(4, LogIn.usuario[0]);
                    stmt.execute();
                    
                    stmt = conn.prepareStatement("UPDATE tb_usuarios SET NIF = ?, Correo_electronico = ?, Password = ? WHERE tb_usuarios.NIF = ?;");
                    stmt.setString(1, sDNI);
                    stmt.setString(2, sCorreo);
                    stmt.setString(3, sContra);
                    stmt.setString(4, LogIn.usuario[0]);
                    stmt.execute();
                  
                    stmt = conn.prepareStatement("UPDATE tb_datos_usuarios SET NIF = ?, Nombre = ?, Apellido1 = ?, Apellido2 = ?, Fecha_nacimiento = ? WHERE tb_datos_usuarios.NIF = ?;");
                    stmt.setString(1, sDNI);
                    stmt.setString(2, sNombre);
                    stmt.setString(3, sApellido1);
                    stmt.setString(4, sApellido2);
                    stmt.setString(5, sFechaNaci);
                    stmt.setString(6, LogIn.usuario[0]);
                    stmt.execute();

                    JOptionPane.showMessageDialog(jPanel1, "Tus datos se han modificado correctamente.");
                    
                    new LogIn().setVisible(true);
                    dispose();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(jPanel1, "El usuario ya existe.");
                TextoDNI.setText("");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void TextoDNICaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoDNICaretUpdate
        // TODO add your handling code here:
        this.sDNI = TextoDNI.getText();
        this.sDNI = Registrar.introducirDNI(sDNI);
        if (this.sDNI.equals("error")) {
            this.bErrorDNI = true;
        } else {
            this.bErrorDNI = false;
        }

        if (this.sDNI.equals(LogIn.usuario[0])) {
            this.bDNIcambiado = false;
        } else {
            this.bDNIcambiado = true;
        }
    }//GEN-LAST:event_TextoDNICaretUpdate

    private void TextoNombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoNombreCaretUpdate
        // TODO add your handling code here:
        this.sNombre = TextoNombre.getText();
        if (sNombre == null || sNombre.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoNombreCaretUpdate

    private void TextoApellido1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoApellido1CaretUpdate
        // TODO add your handling code here:
        this.sApellido1 = TextoApellido1.getText();
        if (sApellido1 == null || sApellido1.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoApellido1CaretUpdate

    private void TextoApellido2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoApellido2CaretUpdate
        // TODO add your handling code here:
        this.sApellido2 = TextoApellido2.getText();
        if (sApellido2 == null || sApellido2.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoApellido2CaretUpdate

    private void TextoFechaNaciCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoFechaNaciCaretUpdate
        // TODO add your handling code here:
        this.sFechaNaci = TextoFechaNaci.getText();
        if (!sFechaNaci.matches("^([0][1-9]|[12][0-9]|3[01])/([0][1-9]|1[0-2])/\\d{4}$")) {
            this.bErrorFecha = true;
        } else {
            this.bErrorFecha = false;
        }
    }//GEN-LAST:event_TextoFechaNaciCaretUpdate

    private void TextoCorreoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoCorreoCaretUpdate
        // TODO add your handling code here:
        this.sCorreo = TextoCorreo.getText();
        if (!sCorreo.matches("^[\\w.-]+@([\\w-]+\\.)+[a-zA-Z]{2,4}$")) {
            this.bErrorEmail = true;
        } else {
            this.bErrorEmail = false;
        }
    }//GEN-LAST:event_TextoCorreoCaretUpdate

    private void TextoContraCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoContraCaretUpdate
        // TODO add your handling code here:
        this.sContra = new String(TextoContra.getPassword());
        if (sContra.length() < 1) {
            this.bErrorContra = true;
        } else {
            this.bErrorContra = false;
        }
    }//GEN-LAST:event_TextoContraCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDatosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextoApellido1;
    private javax.swing.JTextField TextoApellido2;
    private javax.swing.JPasswordField TextoContra;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoDNI;
    private javax.swing.JTextField TextoFechaNaci;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoWInBingo;
    private javax.swing.JTextField TextoWinPrimitiva;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApellido1;
    private javax.swing.JLabel labelApellido2;
    private javax.swing.JLabel labelApellido3;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelFechaNaci;
    private javax.swing.JLabel labelFechaNaci1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreLoteria1;
    private javax.swing.JLabel labelbingoWin;
    private javax.swing.JLabel labelbingoWin1;
    // End of variables declaration//GEN-END:variables
}
