/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_jsiwng_primitiva;

/**
 *
 * @author samue
 */
public class MenuDatosAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuDatosAdmin
     */
    public MenuDatosAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TextoApellido1 = new javax.swing.JTextField();
        TextoApellido2 = new javax.swing.JTextField();
        labelNombreLoteria1 = new javax.swing.JLabel();
        TextoDNI = new javax.swing.JTextField();
        TextoFechaNaci = new javax.swing.JTextField();
        labelDNI = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoWInBingo = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        labelFechaNaci = new javax.swing.JLabel();
        TextoWinPrimitiva = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        labelApellido1 = new javax.swing.JLabel();
        labelApellido2 = new javax.swing.JLabel();
        labelbingoWin = new javax.swing.JLabel();
        labelbingoWin1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        labelNombreLoteria3 = new javax.swing.JLabel();
        TextoDNI2 = new javax.swing.JTextField();
        labelDNI2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        TextoApellido3 = new javax.swing.JTextField();
        TextoApellido4 = new javax.swing.JTextField();
        TextoDNI1 = new javax.swing.JTextField();
        TextoFechaNaci1 = new javax.swing.JTextField();
        labelDNI1 = new javax.swing.JLabel();
        TextoNombre1 = new javax.swing.JTextField();
        TextoWInBingo1 = new javax.swing.JTextField();
        labelNombre1 = new javax.swing.JLabel();
        labelFechaNaci1 = new javax.swing.JLabel();
        TextoWinPrimitiva1 = new javax.swing.JTextField();
        btnModificar2 = new javax.swing.JButton();
        labelApellido3 = new javax.swing.JLabel();
        labelApellido4 = new javax.swing.JLabel();
        labelbingoWin2 = new javax.swing.JLabel();
        labelbingoWin3 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        labelNombreLoteria2 = new javax.swing.JLabel();
        TextoDNI3 = new javax.swing.JTextField();
        labelDNI3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        labelNombreLoteria4 = new javax.swing.JLabel();
        TextoDNI4 = new javax.swing.JTextField();
        labelDNI4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaVer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu admin");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        TextoApellido1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        TextoApellido2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelNombreLoteria1.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria1.setText("Loterias Timo-Theo");
        labelNombreLoteria1.setOpaque(true);

        TextoDNI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDNIActionPerformed(evt);
            }
        });

        TextoFechaNaci.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelDNI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI.setText("DNI:");

        TextoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        TextoWInBingo.setEditable(false);
        TextoWInBingo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoWInBingo.setText("0");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre:");

        labelFechaNaci.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFechaNaci.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNaci.setText("Fecha nacimiento(dd/mm/aaaa):");

        TextoWinPrimitiva.setEditable(false);
        TextoWinPrimitiva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoWinPrimitiva.setText("0");

        btnAgregar.setBackground(new java.awt.Color(0, 153, 0));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Añadir usuario");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        labelApellido1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido1.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido1.setText("Primer apellido:");

        labelApellido2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido2.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido2.setText("Segundo apellido:");

        labelbingoWin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin.setText("Victorias en el bingo:");

        labelbingoWin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin1.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin1.setText("Victorias en la primitiva:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                .addComponent(TextoFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelbingoWin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelbingoWin1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextoWinPrimitiva)
                                    .addComponent(TextoWInBingo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDNI)
                    .addComponent(TextoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido1)
                    .addComponent(TextoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaNaci)
                    .addComponent(TextoFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelbingoWin)
                    .addComponent(TextoWInBingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelbingoWin1)
                    .addComponent(TextoWinPrimitiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAgregar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labelNombreLoteria3.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria3.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria3.setText("Loterias Timo-Theo");
        labelNombreLoteria3.setOpaque(true);

        TextoDNI2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDNI2ActionPerformed(evt);
            }
        });

        labelDNI2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI2.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDNI2.setText("DNI a buscar:");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 153, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(labelDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria3)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(TextoDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNI2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Buscar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        TextoApellido3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        TextoApellido4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        TextoDNI1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDNI1ActionPerformed(evt);
            }
        });

        TextoFechaNaci1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelDNI1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI1.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI1.setText("DNI:");

        TextoNombre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        TextoWInBingo1.setEditable(false);
        TextoWInBingo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelNombre1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre1.setText("Nombre:");

        labelFechaNaci1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFechaNaci1.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNaci1.setText("Fecha nacimiento(dd/mm/aaaa):");

        TextoWinPrimitiva1.setEditable(false);
        TextoWinPrimitiva1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnModificar2.setBackground(new java.awt.Color(0, 153, 0));
        btnModificar2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar2.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar2.setText("Guardar cambios");
        btnModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar2ActionPerformed(evt);
            }
        });

        labelApellido3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido3.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido3.setText("Primer apellido:");

        labelApellido4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido4.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido4.setText("Segundo apellido:");

        labelbingoWin2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin2.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin2.setText("Victorias en el bingo:");

        labelbingoWin3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin3.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin3.setText("Victorias en la primitiva:");

        btnModificar.setBackground(new java.awt.Color(0, 153, 0));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Cargar datos");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        labelNombreLoteria2.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria2.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria2.setText("Loterias Timo-Theo");
        labelNombreLoteria2.setOpaque(true);

        TextoDNI3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDNI3ActionPerformed(evt);
            }
        });

        labelDNI3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI3.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDNI3.setText("DNI actual:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addGap(91, 91, 91))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelApellido4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoApellido4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelFechaNaci1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextoFechaNaci1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelbingoWin2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelbingoWin3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextoWinPrimitiva1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(TextoWInBingo1)))))
                    .addGap(16, 16, 16)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(TextoDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNI3))
                .addGap(0, 435, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelDNI1)
                        .addComponent(TextoDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNombre1)
                        .addComponent(TextoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelApellido3)
                        .addComponent(TextoApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelApellido4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextoApellido4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelFechaNaci1)
                        .addComponent(TextoFechaNaci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelbingoWin2)
                        .addComponent(TextoWInBingo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelbingoWin3)
                        .addComponent(TextoWinPrimitiva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(btnModificar2)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Modificar", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));

        btnEliminar.setBackground(new java.awt.Color(0, 153, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        labelNombreLoteria4.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria4.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria4.setText("Loterias Timo-Theo");
        labelNombreLoteria4.setOpaque(true);

        TextoDNI4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDNI4ActionPerformed(evt);
            }
        });

        labelDNI4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI4.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDNI4.setText("DNI actual:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria4, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(labelDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(TextoDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNI4))
                .addGap(0, 429, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 0));

        btnVer.setBackground(new java.awt.Color(0, 153, 0));
        btnVer.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnVer.setForeground(new java.awt.Color(255, 255, 255));
        btnVer.setText("Mostrar");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        areaVer.setEditable(false);
        areaVer.setBackground(new java.awt.Color(0, 153, 0));
        areaVer.setColumns(20);
        areaVer.setRows(5);
        jScrollPane2.setViewportView(areaVer);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(btnVer)
                .addContainerGap(307, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVer)
                .addGap(24, 24, 24))
        );

        jTabbedPane2.addTab("Mostrar todos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDNIActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void TextoDNI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDNI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDNI1ActionPerformed

    private void btnModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificar2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void TextoDNI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDNI3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDNI3ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TextoDNI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDNI2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDNI2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TextoDNI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDNI4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDNI4ActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDatosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDatosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDatosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDatosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDatosAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextoApellido1;
    private javax.swing.JTextField TextoApellido2;
    private javax.swing.JTextField TextoApellido3;
    private javax.swing.JTextField TextoApellido4;
    private javax.swing.JTextField TextoDNI;
    private javax.swing.JTextField TextoDNI1;
    private javax.swing.JTextField TextoDNI2;
    private javax.swing.JTextField TextoDNI3;
    private javax.swing.JTextField TextoDNI4;
    private javax.swing.JTextField TextoFechaNaci;
    private javax.swing.JTextField TextoFechaNaci1;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoNombre1;
    private javax.swing.JTextField TextoWInBingo;
    private javax.swing.JTextField TextoWInBingo1;
    private javax.swing.JTextField TextoWinPrimitiva;
    private javax.swing.JTextField TextoWinPrimitiva1;
    private javax.swing.JTextArea areaVer;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JButton btnVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelApellido1;
    private javax.swing.JLabel labelApellido2;
    private javax.swing.JLabel labelApellido3;
    private javax.swing.JLabel labelApellido4;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDNI1;
    private javax.swing.JLabel labelDNI2;
    private javax.swing.JLabel labelDNI3;
    private javax.swing.JLabel labelDNI4;
    private javax.swing.JLabel labelFechaNaci;
    private javax.swing.JLabel labelFechaNaci1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombreLoteria1;
    private javax.swing.JLabel labelNombreLoteria2;
    private javax.swing.JLabel labelNombreLoteria3;
    private javax.swing.JLabel labelNombreLoteria4;
    private javax.swing.JLabel labelbingoWin;
    private javax.swing.JLabel labelbingoWin1;
    private javax.swing.JLabel labelbingoWin2;
    private javax.swing.JLabel labelbingoWin3;
    // End of variables declaration//GEN-END:variables
}
