/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej_jsiwng_primitiva;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author samue
 */
public class MenuDatosAdmin extends javax.swing.JFrame {

    private String sDNI;
    private String sDNIinicial;
    private String sNombre;
    private String sApellido1;
    private String sApellido2;
    private String sFechaNaci;
    private String sCorreo;
    private String sContra;
    private String sSexo;
    private String sBingo;
    private String sPrimitiva;
    private boolean bErrorDNI = true;
    private boolean bErrorContra = true;
    private boolean bErrorEmail = true;
    private boolean bErrorFecha = true;
    private boolean bErrorNull = true;
    private boolean bErrorSexo = true;
    private boolean bDNIcambiado = false;

    /**
     * Creates new form MenuDatosAdmin
     */
    public MenuDatosAdmin() {
        initComponents();
    }

    public boolean validar() {
        if (bErrorDNI == true) {
            JOptionPane.showMessageDialog(jPanel1, "DNI inválido. Debe tener 8 números y una letra mayúscula.");
        } else if (bErrorEmail == true) {
            JOptionPane.showMessageDialog(jPanel1, "Correo electronico inválido.");
        } else if (bErrorContra == true) {
            JOptionPane.showMessageDialog(jPanel1, "Contraseña inválida. Debe tener 1 caracter minimo.");
        } else if (bErrorFecha == true) {
            JOptionPane.showMessageDialog(jPanel1, "Fecha nacimiento inválida. Debe tener un formato de fecha (dd/mm/yyyy).");
        } else if (bErrorNull == true) {
            JOptionPane.showMessageDialog(jPanel1, "No puede haber campos vacios.");
        } else if (bErrorSexo == true) {
            JOptionPane.showMessageDialog(jPanel1, "Tiene que seleccionar una de las dos opciones del genero.");
        } else {
            return true;
        }
        return false;
    }

    public void buscar(String dni) {
        try {
            if (!Registrar.SQLComprobarCliente(dni)) {
                throw new Exception();
            }

            var conn = ConexionBaseDatos.getConnection();
            if (conn != null) {
                var stmt = conn.prepareStatement("SELECT * FROM tb_datos_usuarios WHERE NIF = ?");
                stmt.setString(1, dni);
                var resultado = stmt.executeQuery();
                if (resultado.next()) {
                    dni = resultado.getString(1);
                    sNombre = resultado.getString(2);
                    sApellido1 = resultado.getString(3);
                    sApellido2 = resultado.getString(4);
                    sFechaNaci = resultado.getString(5);
                    sSexo = resultado.getString(6);
                }

                stmt = conn.prepareStatement("SELECT * FROM tb_usuarios WHERE NIF=?");
                stmt.setString(1, dni);
                resultado = stmt.executeQuery();
                if (resultado.next()) {
                    sCorreo = resultado.getString(3);
                    sContra = resultado.getString(4);
                }

                stmt = conn.prepareStatement("SELECT * FROM tb_victorias_usuarios WHERE NIF=?");
                stmt.setString(1, dni);
                resultado = stmt.executeQuery();
                if (resultado.next()) {
                    sBingo = resultado.getString(2);
                    sPrimitiva = resultado.getString(3);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(jPanel1, "El usuario no existe." + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelNombreLoteria1 = new javax.swing.JLabel();
        labelDNI = new javax.swing.JLabel();
        TextoFechaNaci1 = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        TextoWInBingo1 = new javax.swing.JTextField();
        labelFechaNaci = new javax.swing.JLabel();
        TextoWinPrimitiva1 = new javax.swing.JTextField();
        labelApellido1 = new javax.swing.JLabel();
        btnModificar1 = new javax.swing.JButton();
        labelApellido2 = new javax.swing.JLabel();
        labelbingoWin = new javax.swing.JLabel();
        labelbingoWin1 = new javax.swing.JLabel();
        TextoApellido1 = new javax.swing.JTextField();
        TextoDNI1 = new javax.swing.JTextField();
        labelFechaNaci2 = new javax.swing.JLabel();
        labelApellido5 = new javax.swing.JLabel();
        TextoCorreo1 = new javax.swing.JTextField();
        TextoContra1 = new javax.swing.JPasswordField();
        TextoNombre1 = new javax.swing.JTextField();
        TextoApellido2 = new javax.swing.JTextField();
        labelSexo = new javax.swing.JLabel();
        btnFemenino = new javax.swing.JRadioButton();
        btnMasculino = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        labelNombreLoteria3 = new javax.swing.JLabel();
        TextoDNI2 = new javax.swing.JTextField();
        labelDNI2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaBuscar = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnModificar2 = new javax.swing.JButton();
        TextoDNI3 = new javax.swing.JTextField();
        labelDNI3 = new javax.swing.JLabel();
        labelDNI5 = new javax.swing.JLabel();
        TextoFechaNaci2 = new javax.swing.JTextField();
        labelNombre2 = new javax.swing.JLabel();
        TextoWInBingo2 = new javax.swing.JTextField();
        labelFechaNaci3 = new javax.swing.JLabel();
        TextoWinPrimitiva2 = new javax.swing.JTextField();
        labelApellido6 = new javax.swing.JLabel();
        btnModificar3 = new javax.swing.JButton();
        labelApellido7 = new javax.swing.JLabel();
        labelbingoWin4 = new javax.swing.JLabel();
        labelbingoWin5 = new javax.swing.JLabel();
        TextoApellido5 = new javax.swing.JTextField();
        TextoDNI5 = new javax.swing.JTextField();
        labelFechaNaci1 = new javax.swing.JLabel();
        labelApellido3 = new javax.swing.JLabel();
        TextoCorreo2 = new javax.swing.JTextField();
        TextoContra2 = new javax.swing.JPasswordField();
        TextoNombre2 = new javax.swing.JTextField();
        labelNombreLoteria5 = new javax.swing.JLabel();
        TextoApellido6 = new javax.swing.JTextField();
        labelbingoWin6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        labelNombreLoteria4 = new javax.swing.JLabel();
        TextoDNI4 = new javax.swing.JTextField();
        labelDNI4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaVer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu admin");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        labelNombreLoteria1.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria1.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria1.setText("Loterias Timo-Theo");
        labelNombreLoteria1.setOpaque(true);

        labelDNI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI.setText("DNI:");

        TextoFechaNaci1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoFechaNaci1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoFechaNaci1CaretUpdate(evt);
            }
        });

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Nombre:");

        TextoWInBingo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoWInBingo1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoWInBingo1CaretUpdate(evt);
            }
        });

        labelFechaNaci.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFechaNaci.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNaci.setText("Fecha nacimiento(dd/mm/aaaa):");

        TextoWinPrimitiva1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoWinPrimitiva1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoWinPrimitiva1CaretUpdate(evt);
            }
        });

        labelApellido1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido1.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido1.setText("Primer apellido:");

        btnModificar1.setBackground(new java.awt.Color(0, 153, 0));
        btnModificar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar1.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar1.setText("Guardar cambios");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });

        labelApellido2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido2.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido2.setText("Segundo apellido:");

        labelbingoWin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin.setText("Victorias en el bingo:");

        labelbingoWin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin1.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin1.setText("Victorias en la primitiva:");

        TextoApellido1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoApellido1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoApellido1CaretUpdate(evt);
            }
        });

        TextoDNI1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoDNI1CaretUpdate(evt);
            }
        });

        labelFechaNaci2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFechaNaci2.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNaci2.setText("Contraseña:");

        labelApellido5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido5.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido5.setText("Correo electronico:");

        TextoCorreo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoCorreo1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoCorreo1CaretUpdate(evt);
            }
        });

        TextoContra1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoContra1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoContra1CaretUpdate(evt);
            }
        });

        TextoNombre1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoNombre1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoNombre1CaretUpdate(evt);
            }
        });

        TextoApellido2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoApellido2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoApellido2CaretUpdate(evt);
            }
        });

        labelSexo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSexo.setForeground(new java.awt.Color(255, 255, 255));
        labelSexo.setText("Sexo");

        btnFemenino.setBackground(new java.awt.Color(0, 102, 0));
        buttonGroup1.add(btnFemenino);
        btnFemenino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFemenino.setForeground(new java.awt.Color(255, 255, 255));
        btnFemenino.setText("Femenino");
        btnFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemeninoActionPerformed(evt);
            }
        });

        btnMasculino.setBackground(new java.awt.Color(0, 102, 0));
        buttonGroup1.add(btnMasculino);
        btnMasculino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMasculino.setForeground(new java.awt.Color(255, 255, 255));
        btnMasculino.setText("Masculino");
        btnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasculinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelFechaNaci2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextoContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(btnFemenino))
                            .addComponent(labelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelbingoWin, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellido5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelbingoWin1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoWinPrimitiva1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCorreo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoWInBingo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoFechaNaci1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(7, 7, 7)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelApellido5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoContra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaNaci2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoWInBingo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelbingoWin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoWinPrimitiva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelbingoWin1))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificar1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFemenino)
                            .addComponent(btnMasculino))))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelDNI)
                        .addComponent(TextoDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNombre)
                        .addComponent(TextoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelApellido1)
                        .addComponent(TextoApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextoApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelFechaNaci)
                        .addComponent(TextoFechaNaci1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(303, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Agregar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labelNombreLoteria3.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria3.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria3.setText("Loterias Timo-Theo");
        labelNombreLoteria3.setOpaque(true);

        TextoDNI2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoDNI2CaretUpdate(evt);
            }
        });

        labelDNI2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI2.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDNI2.setText("DNI a buscar:");

        AreaBuscar.setEditable(false);
        AreaBuscar.setBackground(new java.awt.Color(0, 153, 0));
        AreaBuscar.setColumns(20);
        AreaBuscar.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        AreaBuscar.setForeground(new java.awt.Color(255, 255, 255));
        AreaBuscar.setRows(5);
        jScrollPane1.setViewportView(AreaBuscar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria3)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(TextoDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNI2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 150, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Buscar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        btnModificar2.setBackground(new java.awt.Color(0, 153, 0));
        btnModificar2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnModificar2.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar2.setText("Cargar datos");
        btnModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar2ActionPerformed(evt);
            }
        });

        TextoDNI3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoDNI3CaretUpdate(evt);
            }
        });

        labelDNI3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI3.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDNI3.setText("DNI actual:");

        labelDNI5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI5.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI5.setText("DNI:");

        TextoFechaNaci2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoFechaNaci2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoFechaNaci2CaretUpdate(evt);
            }
        });

        labelNombre2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombre2.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre2.setText("Nombre:");

        TextoWInBingo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoWInBingo2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoWInBingo2CaretUpdate(evt);
            }
        });

        labelFechaNaci3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFechaNaci3.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNaci3.setText("Fecha nacimiento(dd/mm/aaaa):");

        TextoWinPrimitiva2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoWinPrimitiva2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoWinPrimitiva2CaretUpdate(evt);
            }
        });

        labelApellido6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido6.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido6.setText("Primer apellido:");

        btnModificar3.setBackground(new java.awt.Color(0, 153, 0));
        btnModificar3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModificar3.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar3.setText("Guardar cambios");
        btnModificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar3ActionPerformed(evt);
            }
        });

        labelApellido7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido7.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido7.setText("Segundo apellido:");

        labelbingoWin4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin4.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin4.setText("Victorias en el bingo:");

        labelbingoWin5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin5.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin5.setText("Victorias en la primitiva:");

        TextoApellido5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoApellido5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoApellido5CaretUpdate(evt);
            }
        });

        TextoDNI5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoDNI5CaretUpdate(evt);
            }
        });

        labelFechaNaci1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFechaNaci1.setForeground(new java.awt.Color(255, 255, 255));
        labelFechaNaci1.setText("Contraseña:");

        labelApellido3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelApellido3.setForeground(new java.awt.Color(255, 255, 255));
        labelApellido3.setText("Correo electronico:");

        TextoCorreo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoCorreo2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoCorreo2CaretUpdate(evt);
            }
        });

        TextoContra2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoContra2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoContra2CaretUpdate(evt);
            }
        });

        TextoNombre2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoNombre2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoNombre2CaretUpdate(evt);
            }
        });

        labelNombreLoteria5.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria5.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria5.setText("Loterias Timo-Theo");
        labelNombreLoteria5.setOpaque(true);

        TextoApellido6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoApellido6.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoApellido6CaretUpdate(evt);
            }
        });

        labelbingoWin6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelbingoWin6.setForeground(new java.awt.Color(255, 255, 255));
        labelbingoWin6.setText("Victorias en la primitiva:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar2)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDNI5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaNaci1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelbingoWin4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelbingoWin5)
                    .addComponent(labelApellido6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelbingoWin6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaNaci3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelApellido7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificar3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoCorreo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFechaNaci2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoDNI5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoApellido5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TextoApellido6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoContra2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoWInBingo2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoWinPrimitiva2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelbingoWin5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelNombreLoteria5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar2)
                            .addComponent(labelDNI3)
                            .addComponent(TextoDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoDNI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDNI5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoApellido5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellido6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoApellido6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellido7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoFechaNaci2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaNaci3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoCorreo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoContra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaNaci1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoWInBingo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelbingoWin4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextoWinPrimitiva2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelbingoWin6))
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar3)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Modificar", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));

        btnEliminar.setBackground(new java.awt.Color(0, 153, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        labelNombreLoteria4.setBackground(new java.awt.Color(0, 153, 0));
        labelNombreLoteria4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreLoteria4.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreLoteria4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreLoteria4.setText("Loterias Timo-Theo");
        labelNombreLoteria4.setOpaque(true);

        TextoDNI4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextoDNI4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TextoDNI4CaretUpdate(evt);
            }
        });

        labelDNI4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDNI4.setForeground(new java.awt.Color(255, 255, 255));
        labelDNI4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDNI4.setText("DNI actual:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreLoteria4, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(labelDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(labelNombreLoteria4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(TextoDNI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNI4))
                .addGap(0, 502, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 0));

        btnVer.setBackground(new java.awt.Color(0, 153, 0));
        btnVer.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnVer.setForeground(new java.awt.Color(255, 255, 255));
        btnVer.setText("Mostrar");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        areaVer.setEditable(false);
        areaVer.setBackground(new java.awt.Color(0, 153, 0));
        areaVer.setColumns(20);
        areaVer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        areaVer.setForeground(new java.awt.Color(255, 255, 255));
        areaVer.setRows(5);
        jScrollPane2.setViewportView(areaVer);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(btnVer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnVer)
                .addGap(24, 24, 24))
        );

        jTabbedPane2.addTab("Mostrar todos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoFechaNaci1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoFechaNaci1CaretUpdate
        // TODO add your handling code here:
        this.sFechaNaci = TextoFechaNaci1.getText();
        if (!sFechaNaci.matches("^([0][1-9]|[12][0-9]|3[01])/([0][1-9]|1[0-2])/\\d{4}$")) {
            this.bErrorFecha = true;
        } else {
            this.bErrorFecha = false;
        }
    }//GEN-LAST:event_TextoFechaNaci1CaretUpdate

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            try {
                if (Registrar.SQLComprobarCliente(sDNI)) {
                    throw new Exception();
                }

                var conn = ConexionBaseDatos.getConnection();
                if (conn != null) {
                    var stmt = conn.prepareStatement("INSERT INTO tb_datos_usuarios VALUES (?, ?, ?, ?, ?, ?)");
                    stmt.setString(1, sDNI);
                    stmt.setString(2, sNombre);
                    stmt.setString(3, sApellido1);
                    stmt.setString(4, sApellido2);
                    stmt.setString(5, sFechaNaci);
                    stmt.setString(6, sSexo);
                    stmt.execute();

                    stmt = conn.prepareStatement("INSERT INTO tb_usuarios (NIF, Correo_electronico, Password) VALUES (?, ?, ?)");
                    stmt.setString(1, sDNI);
                    stmt.setString(2, sCorreo);
                    stmt.setString(3, sContra);
                    stmt.execute();

                    stmt = conn.prepareStatement("INSERT INTO tb_victorias_usuarios VALUES (?, ?, ?)");
                    stmt.setString(1, sDNI);
                    stmt.setInt(2, Integer.parseInt(sBingo));
                    stmt.setInt(3, Integer.parseInt(sPrimitiva));
                    stmt.execute();

                    JOptionPane.showMessageDialog(jPanel1, "Cliente guardado correctamente.");

                    TextoDNI1.setText("");
                    TextoNombre1.setText("");
                    TextoApellido1.setText("");
                    TextoApellido2.setText("");
                    TextoFechaNaci1.setText("");
                    TextoCorreo1.setText("");
                    TextoContra1.setText("");
                    TextoWInBingo1.setText("");
                    TextoWinPrimitiva1.setText("");
                    buttonGroup1.clearSelection();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(jPanel1, "El usuario ya existe.");
            }
        }
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void TextoApellido1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoApellido1CaretUpdate
        // TODO add your handling code here:
        this.sApellido1 = TextoApellido1.getText();
        if (sApellido1 == null || sApellido1.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoApellido1CaretUpdate

    private void TextoDNI1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoDNI1CaretUpdate
        // TODO add your handling code here:
        this.sDNI = TextoDNI1.getText();
        this.sDNI = Registrar.introducirDNI(sDNI);
        if (this.sDNI.equals("error")) {
            this.bErrorDNI = true;
        } else {
            this.bErrorDNI = false;
        }
    }//GEN-LAST:event_TextoDNI1CaretUpdate

    private void TextoCorreo1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoCorreo1CaretUpdate
        // TODO add your handling code here:
        this.sCorreo = TextoCorreo1.getText();
        if (!sCorreo.matches("^[\\w.-]+@([\\w-]+\\.)+[a-zA-Z]{2,4}$")) {
            this.bErrorEmail = true;
        } else {
            this.bErrorEmail = false;
        }
    }//GEN-LAST:event_TextoCorreo1CaretUpdate

    private void TextoNombre1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoNombre1CaretUpdate
        // TODO add your handling code here:
        this.sNombre = TextoNombre1.getText();
        if (sNombre == null || sNombre.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoNombre1CaretUpdate

    private void TextoApellido2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoApellido2CaretUpdate
        // TODO add your handling code here:
        this.sApellido2 = TextoApellido2.getText();
        if (sApellido2 == null || sApellido2.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoApellido2CaretUpdate

    private void TextoContra1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoContra1CaretUpdate
        // TODO add your handling code here:
        this.sContra = new String(TextoContra1.getPassword());
        if (sContra.length() < 1) {
            this.bErrorContra = true;
        } else {
            this.bErrorContra = false;
        }
    }//GEN-LAST:event_TextoContra1CaretUpdate

    private void TextoWInBingo1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoWInBingo1CaretUpdate
        // TODO add your handling code here:
        this.sBingo = TextoWInBingo1.getText();
    }//GEN-LAST:event_TextoWInBingo1CaretUpdate

    private void TextoWinPrimitiva1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoWinPrimitiva1CaretUpdate
        // TODO add your handling code here:
        this.sPrimitiva = TextoWinPrimitiva1.getText();
    }//GEN-LAST:event_TextoWinPrimitiva1CaretUpdate

    private void btnFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemeninoActionPerformed
        // TODO add your handling code here:
        this.sSexo = "F";
        this.bErrorSexo = false;
    }//GEN-LAST:event_btnFemeninoActionPerformed

    private void btnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasculinoActionPerformed
        // TODO add your handling code here:
        this.sSexo = "M";
        this.bErrorSexo = false;
    }//GEN-LAST:event_btnMasculinoActionPerformed

    private void TextoDNI2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoDNI2CaretUpdate
        // TODO add your handling code here:
        this.sDNI = TextoDNI2.getText();
        this.sDNI = Registrar.introducirDNI(sDNI);
        if (this.sDNI.equals("error")) {
            this.bErrorDNI = true;
        } else {
            this.bErrorDNI = false;
        }
    }//GEN-LAST:event_TextoDNI2CaretUpdate

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (bErrorDNI == true) {
            JOptionPane.showMessageDialog(jPanel1, "DNI inválido. Debe tener 8 números y una letra mayúscula.");
        } else {
            buscar(sDNI);
            AreaBuscar.setText(" DNI: " + sDNI + "\n"
                    + " Nombre: " + sNombre + "\n"
                    + " Apellidos: " + sApellido1 + " " + sApellido2 + "\n"
                    + " Fecha de nacimiento: " + sFechaNaci + "\n"
                    + " Sexo: " + sSexo + "\n"
                    + " Correo electronico: " + sCorreo + "\n"
                    + " Contraseña: " + sContra + "\n"
                    + " Victorias en el Bingo: " + sBingo + "\n"
                    + " Victorias en la Primitiva: " + sPrimitiva);

            TextoDNI2.setText("");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void TextoDNI3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoDNI3CaretUpdate
        // TODO add your handling code here:
        this.sDNIinicial = TextoDNI3.getText();
        this.sDNI = this.sDNIinicial;
        this.sDNIinicial = Registrar.introducirDNI(sDNIinicial);
        if (this.sDNIinicial.equals("error")) {
            this.bErrorDNI = true;
        } else {
            this.bErrorDNI = false;
        }
    }//GEN-LAST:event_TextoDNI3CaretUpdate

    private void TextoDNI5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoDNI5CaretUpdate
        // TODO add your handling code here:
        this.sDNI = TextoDNI5.getText();
        this.sDNI = Registrar.introducirDNI(sDNI);
        if (this.sDNI.equals("error")) {
            this.bErrorDNI = true;
        } else {
            this.bErrorDNI = false;
        }
        if (this.sDNI.equals(sDNIinicial)) {
            this.bDNIcambiado = false;
        } else {
            this.bDNIcambiado = true;
        }
    }//GEN-LAST:event_TextoDNI5CaretUpdate

    private void TextoNombre2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoNombre2CaretUpdate
        // TODO add your handling code here:
        this.sNombre = TextoNombre2.getText();
        if (sNombre == null || sNombre.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoNombre2CaretUpdate

    private void TextoApellido5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoApellido5CaretUpdate
        // TODO add your handling code here:
        this.sApellido1 = TextoApellido5.getText();
        if (sApellido1 == null || sApellido1.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoApellido5CaretUpdate

    private void TextoApellido6CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoApellido6CaretUpdate
        // TODO add your handling code here:
        this.sApellido2 = TextoApellido6.getText();
        if (sApellido2 == null || sApellido2.trim().isEmpty()) {
            this.bErrorNull = true;
        } else {
            this.bErrorNull = false;
        }
    }//GEN-LAST:event_TextoApellido6CaretUpdate

    private void TextoFechaNaci2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoFechaNaci2CaretUpdate
        // TODO add your handling code here:
        this.sFechaNaci = TextoFechaNaci2.getText();
        if (!sFechaNaci.matches("^([0][1-9]|[12][0-9]|3[01])/([0][1-9]|1[0-2])/\\d{4}$")) {
            this.bErrorFecha = true;
        } else {
            this.bErrorFecha = false;
        }
    }//GEN-LAST:event_TextoFechaNaci2CaretUpdate

    private void TextoCorreo2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoCorreo2CaretUpdate
        // TODO add your handling code here:
        this.sCorreo = TextoCorreo2.getText();
        if (!sCorreo.matches("^[\\w.-]+@([\\w-]+\\.)+[a-zA-Z]{2,4}$")) {
            this.bErrorEmail = true;
        } else {
            this.bErrorEmail = false;
        }
    }//GEN-LAST:event_TextoCorreo2CaretUpdate

    private void TextoContra2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoContra2CaretUpdate
        // TODO add your handling code here:
        this.sContra = new String(TextoContra2.getPassword());
        if (sContra.length() < 1) {
            this.bErrorContra = true;
        } else {
            this.bErrorContra = false;
        }
    }//GEN-LAST:event_TextoContra2CaretUpdate

    private void TextoWInBingo2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoWInBingo2CaretUpdate
        // TODO add your handling code here:
        this.sBingo = TextoWInBingo2.getText();

    }//GEN-LAST:event_TextoWInBingo2CaretUpdate

    private void TextoWinPrimitiva2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoWinPrimitiva2CaretUpdate
        // TODO add your handling code here:
        this.sPrimitiva = TextoWinPrimitiva2.getText();

    }//GEN-LAST:event_TextoWinPrimitiva2CaretUpdate

    private void btnModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar2ActionPerformed
        // TODO add your handling code here:
        try {
            if (!Registrar.SQLComprobarCliente(sDNI)) {
                throw new Exception();
            }
            buscar(sDNI);

            TextoDNI5.setText(sDNI);
            TextoNombre2.setText(sNombre);
            TextoApellido5.setText(sApellido1);
            TextoApellido6.setText(sApellido2);
            TextoFechaNaci2.setText(sFechaNaci);
            TextoCorreo2.setText(sCorreo);
            TextoContra2.setText(sContra);
            TextoWInBingo2.setText(sBingo);
            TextoWinPrimitiva2.setText(sPrimitiva);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(jPanel1, "El usuario no existe.");
            TextoDNI3.setText("");
            TextoDNI5.setText("");
            TextoNombre2.setText("");
            TextoApellido5.setText("");
            TextoApellido6.setText("");
            TextoFechaNaci2.setText("");
            TextoCorreo2.setText("");
            TextoContra2.setText("");
            TextoWInBingo2.setText("");
            TextoWinPrimitiva2.setText("");
        }

    }//GEN-LAST:event_btnModificar2ActionPerformed

    private void btnModificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar3ActionPerformed
        // TODO add your handling code here:
        bErrorSexo = false;
        if (validar()) {
            try {
                if (bDNIcambiado) {
                    if (Registrar.SQLComprobarCliente(sDNI)) {
                        throw new Exception();
                    }
                }

                var conn = ConexionBaseDatos.getConnection();
                if (conn != null) {

                    var stmt = conn.prepareStatement("UPDATE tb_victorias_usuarios SET NIF = ?, victorias_bingo = ?, victorias_primitiva = ? WHERE tb_victorias_usuarios.NIF = ?;");
                    stmt.setString(1, sDNI);
                    stmt.setInt(2, Integer.parseInt(LogIn.wins_usuario[0]));
                    stmt.setInt(3, Integer.parseInt(LogIn.wins_usuario[1]));
                    stmt.setString(4, sDNIinicial);
                    stmt.execute();

                    stmt = conn.prepareStatement("UPDATE tb_usuarios SET NIF = ?, Correo_electronico = ?, Password = ? WHERE tb_usuarios.NIF = ?;");
                    stmt.setString(1, sDNI);
                    stmt.setString(2, sCorreo);
                    stmt.setString(3, sContra);
                    stmt.setString(4, sDNIinicial);
                    stmt.execute();

                    stmt = conn.prepareStatement("UPDATE tb_datos_usuarios SET NIF = ?, Nombre = ?, Apellido1 = ?, Apellido2 = ?, Fecha_nacimiento = ? WHERE tb_datos_usuarios.NIF = ?;");
                    stmt.setString(1, sDNI);
                    stmt.setString(2, sNombre);
                    stmt.setString(3, sApellido1);
                    stmt.setString(4, sApellido2);
                    stmt.setString(5, sFechaNaci);
                    stmt.setString(6, sDNIinicial);
                    stmt.execute();

                    JOptionPane.showMessageDialog(jPanel1, "Tus datos se han modificado correctamente.");

                    TextoDNI3.setText("");
                    TextoDNI5.setText("");
                    TextoNombre2.setText("");
                    TextoApellido5.setText("");
                    TextoApellido6.setText("");
                    TextoFechaNaci2.setText("");
                    TextoCorreo2.setText("");
                    TextoContra2.setText("");
                    TextoWInBingo2.setText("");
                    TextoWinPrimitiva2.setText("");

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(jPanel1, "El usuario ya existe." + ex.getMessage());
                TextoDNI5.setText("");
            }
        }
    }//GEN-LAST:event_btnModificar3ActionPerformed

    private void TextoDNI4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TextoDNI4CaretUpdate
        // TODO add your handling code here:
        this.sDNI = TextoDNI4.getText();
        this.sDNI = Registrar.introducirDNI(sDNI);
        if (this.sDNI.equals("error")) {
            this.bErrorDNI = true;
        } else {
            this.bErrorDNI = false;
        }
    }//GEN-LAST:event_TextoDNI4CaretUpdate

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (bErrorDNI == true) {
            JOptionPane.showMessageDialog(jPanel1, "DNI inválido. Debe tener 8 números y una letra mayúscula.");
        } else {
            try {
                if (!Registrar.SQLComprobarCliente(sDNI)) {
                    throw new Exception();
                }

                var conn = ConexionBaseDatos.getConnection();
                if (conn != null) {

                    var stmt = conn.prepareStatement("DELETE FROM tb_victorias_usuarios WHERE tb_victorias_usuarios.NIF = ?;");
                    stmt.setString(1, sDNI);
                    stmt.execute();

                    stmt = conn.prepareStatement("DELETE FROM tb_usuarios WHERE tb_usuarios.NIF = ?;");
                    stmt.setString(1, sDNI);
                    stmt.execute();

                    stmt = conn.prepareStatement("DELETE FROM tb_datos_usuarios WHERE NIF = ?");
                    stmt.setString(1, sDNI);
                    stmt.execute();

                    JOptionPane.showMessageDialog(jPanel1, "Se ha eliminado al usuario correctamenta.");

                    TextoDNI4.setText("");

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(jPanel1, "El usuario no existe.");
                TextoDNI4.setText("");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        try {
            var conn = ConexionBaseDatos.getConnection();
            var stmt = conn.prepareStatement(
                    "SELECT d.NIF, d.Nombre, d.Apellido1, d.Apellido2, d.Fecha_nacimiento, d.Sexo, "
                    + "u.Correo_electronico, u.Password, v.victorias_bingo, v.victorias_primitiva "
                    + "FROM tb_datos_usuarios d "
                    + "JOIN tb_usuarios u ON d.NIF = u.NIF "
                    + "JOIN tb_victorias_usuarios v ON d.NIF = v.NIF"
            );

            var rs = stmt.executeQuery();
            StringBuilder sb = new StringBuilder();

            // Cabecera
            sb.append(String.format("%-10s %-10s %-22s %-12s %-6s %-25s %-15s %-7s %-9s\n",
                    "DNI", "Nombre", "Apellidos", "Nacimiento", "Sexo", "Correo", "Contraseña", "Bingo", "Primitiva"));
            sb.append("-------------------------------------------------------------------------------------------------------------------------------------------\n");

            while (rs.next()) {
                String sDNI = rs.getString("NIF");
                String sNombre = rs.getString("Nombre");
                String sApellido1 = rs.getString("Apellido1");
                String sApellido2 = rs.getString("Apellido2");
                String sFechaNaci = rs.getString("Fecha_nacimiento");
                String sSexo = rs.getString("Sexo");
                String sCorreo = rs.getString("Correo_electronico");
                String sContra = rs.getString("Password");
                int sBingo = rs.getInt("victorias_bingo");
                int sPrimitiva = rs.getInt("victorias_primitiva");

                String apellidos = sApellido1 + " " + sApellido2;

                sb.append(String.format("%-10s %-10s %-22s %-12s %-6s %-25s %-15s %-7d %-9d\n",
                        sDNI, sNombre, apellidos, sFechaNaci, sSexo, sCorreo, sContra, sBingo, sPrimitiva));
            }
 
            areaVer.setText(sb.toString());
        } catch (SQLException ex) {
            areaVer.setText("Error al cargar datos: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDatosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDatosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDatosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDatosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDatosAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaBuscar;
    private javax.swing.JTextField TextoApellido1;
    private javax.swing.JTextField TextoApellido2;
    private javax.swing.JTextField TextoApellido5;
    private javax.swing.JTextField TextoApellido6;
    private javax.swing.JPasswordField TextoContra1;
    private javax.swing.JPasswordField TextoContra2;
    private javax.swing.JTextField TextoCorreo1;
    private javax.swing.JTextField TextoCorreo2;
    private javax.swing.JTextField TextoDNI1;
    private javax.swing.JTextField TextoDNI2;
    private javax.swing.JTextField TextoDNI3;
    private javax.swing.JTextField TextoDNI4;
    private javax.swing.JTextField TextoDNI5;
    private javax.swing.JTextField TextoFechaNaci1;
    private javax.swing.JTextField TextoFechaNaci2;
    private javax.swing.JTextField TextoNombre1;
    private javax.swing.JTextField TextoNombre2;
    private javax.swing.JTextField TextoWInBingo1;
    private javax.swing.JTextField TextoWInBingo2;
    private javax.swing.JTextField TextoWinPrimitiva1;
    private javax.swing.JTextField TextoWinPrimitiva2;
    private javax.swing.JTextArea areaVer;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JRadioButton btnFemenino;
    private javax.swing.JRadioButton btnMasculino;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JButton btnModificar3;
    private javax.swing.JButton btnVer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelApellido1;
    private javax.swing.JLabel labelApellido2;
    private javax.swing.JLabel labelApellido3;
    private javax.swing.JLabel labelApellido5;
    private javax.swing.JLabel labelApellido6;
    private javax.swing.JLabel labelApellido7;
    private javax.swing.JLabel labelDNI;
    private javax.swing.JLabel labelDNI2;
    private javax.swing.JLabel labelDNI3;
    private javax.swing.JLabel labelDNI4;
    private javax.swing.JLabel labelDNI5;
    private javax.swing.JLabel labelFechaNaci;
    private javax.swing.JLabel labelFechaNaci1;
    private javax.swing.JLabel labelFechaNaci2;
    private javax.swing.JLabel labelFechaNaci3;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelNombreLoteria1;
    private javax.swing.JLabel labelNombreLoteria3;
    private javax.swing.JLabel labelNombreLoteria4;
    private javax.swing.JLabel labelNombreLoteria5;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel labelbingoWin;
    private javax.swing.JLabel labelbingoWin1;
    private javax.swing.JLabel labelbingoWin4;
    private javax.swing.JLabel labelbingoWin5;
    private javax.swing.JLabel labelbingoWin6;
    // End of variables declaration//GEN-END:variables
}
